<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="AWSSDK.Core" Version="4.0.3.26" />
	<PackageReference Include="AWSSDK.S3" Version="4.0.20.2" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.5" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
	<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
	<PackageReference Include="MongoDB.Driver" Version="3.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Estudaki.Commons.Core\Estudaki.Commons.Core.csproj" />
    <ProjectReference Include="..\..\Modules\Comunications\Estudaki.Modules.Comunications.Infrastructure\Estudaki.Modules.Comunications.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\Estudaki.Modules.Identity.Infrastructure\Estudaki.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Modules\Questions\Estudaki.Modules.Questions.Infrastructure\Estudaki.Modules.Questions.Infrastructure.csproj" />
  </ItemGroup>

</Project>
