<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
	<PackageReference Include="MongoDB.Driver" Version="3.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Estudaki.Modules.Comunications.Application\Estudaki.Modules.Comunications.Application.csproj" />
  </ItemGroup>

</Project>
