<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
	  <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.11" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Estudaki.Commons.Core\Estudaki.Commons.Core.csproj" />
    <ProjectReference Include="..\Estudaki.Modules.Identity.Domain\Estudaki.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\Estudaki.Modules.Identity.Application\Estudaki.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\Estudaki.Modules.Identity.Adapter\Estudaki.Modules.Identity.Adapter.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Repositories\" />
  </ItemGroup>

</Project>
