import sanitizeHtml from 'sanitize-html';

const katexMathMlTags = [
    'math',
    'semantics',
    'annotation',
    'mrow',
    'mi',
    'mn',
    'mo',
    'mtext',
    'mspace',
    'mstyle',
    'mfrac',
    'msqrt',
    'mroot',
    'msub',
    'msup',
    'msubsup',
    'munder',
    'mover',
    'munderover',
    'mtable',
    'mtr',
    'mtd',
    'menclose',
    'mphantom',
    'mpadded',
    'mglyph'
];
const katexSvgTags = ['svg', 'path', 'line'];

const sanitizeOptions: sanitizeHtml.IOptions = {
    allowedTags: sanitizeHtml.defaults.allowedTags.concat([
        'div',
        'span',
        'p',
        'br',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'ol',
        'ul',
        'li',
        'blockquote',
        'pre',
        'code',
        'sub',
        'sup',
        's',
        'img',
        'iframe',
        'video',
        'audio',
        'source',
        ...katexMathMlTags,
        ...katexSvgTags
    ]),
    allowedAttributes: {
        ...sanitizeHtml.defaults.allowedAttributes,
        '*': [
            'class',
            'style',
            'dir',
            'data-*',
            'xmlns',
            'display',
            'encoding',
            'mathvariant',
            'mathsize',
            'mathcolor',
            'mathbackground',
            'stretchy',
            'fence',
            'separator',
            'lspace',
            'rspace',
            'minsize',
            'maxsize',
            'largeop',
            'movablelimits',
            'accent',
            'accentunder',
            'linethickness',
            'rowspacing',
            'columnalign',
            'columnlines',
            'columnspacing',
            'rowlines',
            'notation',
            'scriptlevel',
            'displaystyle',
            'voffset',
            'depth',
            'valign',
            'alt',
            'href',
            'src',
            'width',
            'height',
            'viewbox',
            'preserveaspectratio',
            'd',
            'x1',
            'y1',
            'x2',
            'y2',
            'stroke-width'
        ]
    },
    allowedSchemes: ['http', 'https', 'mailto'],
    allowVulnerableTags: false
};

export function sanitizeQuestionContent(content: string): string {
    return sanitizeHtml(content, sanitizeOptions);
}